
const NotFoundPage = () => {
  return (
    <div className="flex h-screen w-full flex-col items-center justify-center bg-gray-100 p-4 text-center">
      <h1 className="text-9xl font-bold text-gray-800">404</h1>
      <h2 className="mt-4 text-2xl font-semibold text-gray-700">Oops! Page not found</h2>
      <p className="mt-2 text-gray-500">The page you are looking for does not exist.</p>
      
      <a
        href="/"
        className="mt-6 rounded-lg bg-blue-500 px-6 py-3 text-white transition hover:bg-blue-600"
      >
        Go Back Home
      </a>
    </div>
  );
}
export default NotFoundPage;  // This was generated by chat gpt I have included the link to the the entire chat. https://chatgpt.com/share/67e2f60d-c408-800f-a241-84f6ee4ad6c3